### ISSUE TITLE
add comparison with other libraries for peak detection

### ISSUE THREAD

**Issue by LegrandNico** [devnums/pyheartlib#10]
As the added value of the package is to facilitate the use of machine learning and deep learning methods to analyse ECG signal, it would be useful to see how this relate to other methods, especially methods that are simpler. I would suggest a comparison with the peak detection algorithms provided by [Neurokit2](https://github.com/neuropsychology/NeuroKit) and [SleepECG](https://github.com/cbrnr/sleepecg).

This issue is related to the review of the package for JOSS (see [here](https://github.com/openjournals/joss-reviews/issues/5792)).

**Comment by devnums** [comment]
Thank you for your suggestion. I have edited the paper, please take a look at it [here](https://github.com/devnums/pyheartlib/blob/paper-rev/paper/paper.pdf) and let me know if that's what you mean.
