### ISSUE TITLE
What is the relationship between examples dataset and model?

### ISSUE THREAD

**Issue by cudmore** [devnums/pyheartlib#14]
You describe how to create a number of [dataset](https://pyheartlib.readthedocs.io/en/latest/examples/dataset/dataset.html) including: arrhythmia, inter-patient beat, intra-patient beat, and Rpeak.

You then describe how to create a [beat detection](https://pyheartlib.readthedocs.io/en/latest/examples/model/model.html) model in a few steps like: data preparation, training, inference, and results.

As a user, I do not understand the connection between me running the code to create these 4 different **dataset(s)** and then the **model** code with an additional 4 steps.

Can you create a new page(s) in your documentation to explain this to me?

When I run the dataset code, is that used in the model code? If so, how?

**Comment by devnums** [comment]
The documentation now includes a page that explains all the examples.
https://pyheartlib.readthedocs.io/en/latest/examples/examples.html

Both examples 3 and 4 show how the `RpeakData` class can be used to create datasets. However, in Example 4, there are steps to use the datasets for training a deep learning model. In both examples, the `RpeakData` class is used, but the output datasets are different. Example 4 demonstrates a specific use case for it.
