### ISSUE TITLE
Test model on separate dataset

### ISSUE THREAD

**Issue by Bsingstad** [devnums/pyheartlib#17]
As far as I can see you are training, testing and validating your model on the same dataset; MIT BIH Arrhythmia Database. To validate that this model also works on other datasets (possibly using other hardware, measurement set up and so on) would be a huge strange for this software package in my opinion.

**Comment by devnums** [comment]
This software can be used with other datasets and different machine learning models. It is only required that the datasets have a similar format and structure to the MIT-BIH Arrhythmia Database.

**Comment by Bsingstad** [comment]
Ok, then it would be nice of you to show this in the paper. From what you have showed we can't know if the model is overfitted to the specific dataset (MIT-BIH Arrhythmia Database).
