### ISSUE TITLE
add more information to the contribution guidelines

### ISSUE THREAD

**Issue by LegrandNico** [devnums/pyheartlib#8]
The contribution guidelines could be detailed, adding for example instructions on how to contribute to the documentation and run the tests. Using a public platform for questions and help is probably preferable over email exchanges (also for the maintainer).

See this example of guidelines from another popular repository [here](https://github.com/blackjax-devs/blackjax/blob/main/CONTRIBUTING.md).

This issue is related to the review of the package for JOSS (see [here](https://github.com/openjournals/joss-reviews/issues/5792)).

**Comment by devnums** [comment]
Thanks for your comment. The file has been updated. Please check it on the branch: paper
[contributing.md](https://github.com/devnums/pyheartlib/blob/paper/CONTRIBUTING.md)

**Comment by LegrandNico** [comment]
It looks like the discord link is broken, maybe this could be removed?

**Comment by devnums** [comment]
You are right, I have created a new permanent link. [CONTRIBUTING.md](https://github.com/devnums/pyheartlib/blob/paper-rev/CONTRIBUTING.md)
